import type { ClientWithLanguages } from '@/api/client/clientModel';

export const mockClients: ClientWithLanguages[] = [
    {
        id: 1,
        firstName: 'John',
        middleName: 'Doe',
        lastName: 'Smith',
        email: 'john@example.com',
        dob: '1990-01-01',
        createdAt: '2021-01-01',
        updatedAt: '2021-01-01',
        fundingSource: 'NDIS',
        languages: [
            {
                id: 1,
                name: 'English',
                isPrimary: true,
            },
            {
                id: 2,
                name: 'Spanish',
                isPrimary: false,
            },
        ],
    },
    {
        id: 2,
        firstName: 'Jane',
        middleName: 'Doe',
        lastName: 'Smith',
        email: 'jane@example.com',
        dob: '1990-01-01',
        createdAt: '2021-01-01',
        updatedAt: '2021-01-01',
        fundingSource: 'NDIS',
        languages: [
            {
                id: 3,
                name: 'French',
                isPrimary: true,
            },
            {
                id: 1,
                name: 'English',
                isPrimary: false,
            },
        ],
    },
];

export const mockUnmappedClients = [
    {
        id: 1,
        firstName: 'John',
        middleName: 'Doe',
        lastName: 'Smith',
        email: 'john@example.com',
        dob: '1990-01-01',
        createdAt: '2021-01-01',
        updatedAt: '2021-01-01',
        fundingSource: 'NDIS',
        languageId: 1,
        languageName: 'English',
        isPrimary: true,
    },
    {
        id: 1,
        firstName: 'John',
        middleName: 'Doe',
        lastName: 'Smith',
        email: 'john@example.com',
        dob: '1990-01-01',
        createdAt: '2021-01-01',
        updatedAt: '2021-01-01',
        fundingSource: 'NDIS',
        languageId: 2,
        languageName: 'Spanish',
        isPrimary: false,
    },
    {
        id: 2,
        firstName: 'Jane',
        middleName: 'Doe',
        lastName: 'Smith',
        email: 'jane@example.com',
        dob: '1990-01-01',
        createdAt: '2021-01-01',
        updatedAt: '2021-01-01',
        fundingSource: 'NDIS',
        languageId: 3,
        languageName: 'French',
        isPrimary: true,
    },
    {
        id: 2,
        firstName: 'Jane',
        middleName: 'Doe',
        lastName: 'Smith',
        email: 'jane@example.com',
        dob: '1990-01-01',
        createdAt: '2021-01-01',
        updatedAt: '2021-01-01',
        fundingSource: 'NDIS',
        languageId: 1,
        languageName: 'English',
        isPrimary: false,
    },
];
